### ISSUE TITLE
Peer dependency issues in 18.1

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-context#12]
New peer dependencies were added in the 18.1.0 release: https://github.com/digitalbazaar/bedrock-ledger-context/blob/main/CHANGELOG.md#1810---2021-06-30

If these new dependencies should be peer dependencies and not regular dependencies, then this should have been released as a breaking major release as it breaks existing software that does not include these peer dependencies.

The question then arises whether these additional context modules should be treated as peer dependencies or regular dependencies.

I would suggest that this issue could be resolved by a patch a 18.1.1 patch release that makes the new context dependencies regular dependencies.

https://github.com/digitalbazaar/bedrock-ledger-context/blob/main/package.json#L28-L29

**Comment by dlongley** [comment]
I agree that this should have been a major release -- and it was listed as such in the PR that was approved (https://github.com/digitalbazaar/bedrock-ledger-context/pull/11/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR3). I'm guessing it was just a mistake that it went out as a minor one?

**Comment by dlongley** [comment]
I think the resolution should probably be to release 18.1.1 that is based off of 18.0 -- and then do a clean 19.0 release. But, if that's not necessary and the non-peer deps thing would work, +1 to that instead since it sounds simpler.

**Comment by mattcollier** [comment]
Making 18.1.1 PR now.
