### ISSUE TITLE
Unreleased commits.

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-context#3]
@dlongley I see some commits on master that have not been released.  Should that be released, and if so, what sort of release.  Seems to me that as it relates to a content addressable systems, every release of a context module is a major/breaking release.  What are your thoughts?

**Comment by dlongley** [comment]
I'm comfortable with a major release of this after the end of next week.

**Comment by dlongley** [comment]
Actually, if it's a major release, that's fine now.

**Comment by mattcollier** [comment]
@dlongley I will do a major release.  I guess my real question is when are we going to freeze `webledger-v1.jsonld`?

**Comment by dlongley** [comment]
@mattcollier, I expect us to freeze it when we do the veres one release.

**Comment by mattcollier** [comment]
v2 released.
